exports.profileList = [
    {
      id: '50e9660f-91d6-47a6-9458-5ffc4c00b345',
      name: 'Michael Jackson',
      description: 'Adolph Larrue Martinez III',
      mbti: 'ISFJ,',
      enneagram: '9w3,',
      variant: 'sp/so,',
      tritype: '2,',
      socionics: 'see,',
      sloan: 'rcoen,',
      psyche: 'fevl,',
      image: 'https://soulverse.boo.world/images/1.png',
    },
    {
      id: '50e9660f-91d6-47a6-9458-5ffc4c00b789',
      name: 'Elvis',
      description: 'Adolph Larrue Martinez III',
      mbti: 'ISFJ,',
      enneagram: '9w3,',
      variant: 'sp/so,',
      tritype: '2,',
      socionics: 'see,',
      sloan: 'rcoen,',
      psyche: 'fevl,',
      image: 'https://soulverse.boo.world/images/1.png',
    },
    {
      id: '50e9660f-91d6-47a6-9458-5ffc4c00bfgt',
      name: 'Muddy Waters',
      description: 'Adolph Larrue Martinez III',
      mbti: 'ISFJ,',
      enneagram: '9w3,',
      variant: 'sp/so,',
      tritype: '2,',
      socionics: 'see,',
      sloan: 'rcoen,',
      psyche: 'fevl,',
      image: 'https://soulverse.boo.world/images/1.png',
    },
    {
      id: '50e9660f-91d6-47a6-9458-5ffc4c003421',
      name: 'James Brown',
      description: 'Adolph Larrue Martinez III',
      mbti: 'ISFJ,',
      enneagram: '9w3,',
      variant: 'sp/so,',
      tritype: '2,',
      socionics: 'see,',
      sloan: 'rcoen,',
      psyche: 'fevl,',
      image: 'https://soulverse.boo.world/images/1.png',
    },
    {
      id: '50e9660f-91d6-47a6-9458-5ffc4ceerraa',
      name: 'Temptations',
      description: 'Adolph Larrue Martinez III',
      mbti: 'ISFJ,',
      enneagram: '9w3,',
      variant: 'sp/so,',
      tritype: '2,',
      socionics: 'see,',
      sloan: 'rcoen,',
      psyche: 'fevl,',
      image: 'https://soulverse.boo.world/images/1.png',
    },
    {
      id: '50e9660f-91d6-47a6-9458-5frfgwssb1aa',
      name: 'Marvin Gaye',
      description: 'Adolph Larrue Martinez III',
      mbti: 'ISFJ,',
      enneagram: '9w3,',
      variant: 'sp/so,',
      tritype: '2,',
      socionics: 'see,',
      sloan: 'rcoen,',
      psyche: 'fevl,',
      image: 'https://soulverse.boo.world/images/1.png',
    },
    {
      id: '50e9660f-91d6-47a6-9458-5tt06ytr0b1aa',
      name: 'Lionel Richie',
      description: 'Adolph Larrue Martinez III',
      mbti: 'ISFJ,',
      enneagram: '9w3,',
      variant: 'sp/so,',
      tritype: '2,',
      socionics: 'see,',
      sloan: 'rcoen,',
      psyche: 'fevl,',
      image: 'https://soulverse.boo.world/images/1.png',
    }
  ];